Move workflow env files from ufs srw app
ufs-community/regional_workflow pull request #679
Opened 2022-02-18 18:08 UTC by chan-hoo

## DESCRIPTION OF CHANGES: 
The workflow environment files in the 'ufs-srweather-app/env' directory are moved to the 'env' directory.

## ISSUE: 
Fixes issue mentioned in #678.

2022-02-21 22:25 UTC, RatkoVasic-NOAA approved these changes
Looks good to me.

2022-02-22 19:49 UTC, gsketefian commented
@chan-hoo I think you can just delete the `docs` directory since all documentation is now in the `ufs-srweather-app` repo.

2022-02-22 19:53 UTC, gsketefian commented
@chan-hoo There is a comment block at the top of `ush/config_defaults.sh` that references the latest NCO standards document (lines 15-32).  Do you mind updating that from the 2019 to the 2022 standard?  Thanks.

2022-02-22 20:09 UTC, chan-hoo commented
@gsketefian, updated.

2022-02-24 01:24 UTC, JeffBeck-NOAA requested changes

2022-02-24 01:24 UTC, JeffBeck-NOAA commented on ush/launch_FV3LAM_wflow.sh
>  module purge
I think we want to keep this as what's on the left-hand side, correct?  Also, it should really be ${SRW_APP_TOP_DIR} (not SR_WX_APP...), but that's beyond the scope of this PR!

2022-02-28 14:03 UTC, closed without merging