Added support for RRFS_v1nssl to develop branch
ufs-community/regional_workflow pull request #708
Opened 2022-03-21 20:40 UTC by ywangwof

## DESCRIPTION OF CHANGES: 
Added support for the NSSL CCPP suite, **_RRFS_v1nssl_** in the develop branch.

## TESTS CONDUCTED: 
Tested on Odin using Intel 2020 and the GST model data on 20190615, modified based on the community workflow predefined grid **_RRFS_CONUS_3km_**.

## DEPENDENCIES:
It will require the **ufs-weather-model** hash `# 38aa6340 - (2022-03-04)` or later because it is the commit that adds `NSSL Microphysics support (#1032)`.

## DOCUMENTATION:
Will study the document to update when the CCPP suite name is finalized.

## MODIFIED AND NEW FILES:

> scripts/exregional_make_ics.sh
> scripts/exregional_make_lbcs.sh
> ush/templates/FV3.input.yml
> ush/templates/diag_table.FV3_RRFS_v1nssl
> ush/templates/field_table.FV3_RRFS_v1nssl
> ush/valid_param_vals.sh

## ISSUES:
- This addition will require an upgrade of the **ufs-weather-model** repository in the App level (see above).
- As for suite name, do we want "FV3_WoFS"? Or "FV3_RRFS_WoFS"?
- This suite currently uses Noahmp. Not sure whether will Noah-lsm be desired?
- The runtime files for this workflow contains new sections for HAILCAST output. A PR for the code update of **GFDL_atmos_cubed_sphere** is under-review. They will not have an impact even the FV3 core still does not support this feature.

## CONTRIBUTORS (optional): 
Ted Mansell (@MicroTed) provided the initial runtime files for this workflow.

2022-03-21 22:43 UTC, ligiabernardet requested changes
Thank you for this PR. My understanding from Curtis' [spreadsheet](https://docs.google.com/spreadsheets/d/1m8RYA485SyMe0BSLya0rUJZKABOQMXJf7PVzufgulIQ/edit#gid=0) is that the WoFS suite should use Noah LSM (instead of NoahMP), which will require PRs to fv3atm and ufs-weather-model to either change or add a suite and associated regression test. 
Regarding the name of the suite, FV3_WoFS seems reasonable to me, but I am open to alternatives.

2022-03-21 23:11 UTC, MicroTed commented
>  the WoFS suite should use Noah LSM (instead of NoahMP), which will require PRs to fv3atm and ufs-weather-model to either change or add a suite and associated regression test.

Yes, the v1nssl suite is a stand-in at the moment. We will probably just replace that suite in fv3atm with FV3_WoFS (or whatever) and then also convert the current RT items to use the new suite.

The question I have is about the gravity wave drag settings. Our current suite (FV3_RRFS_v1nssl_lsmnoah, for the daily NSSL-FV3 runs) uses Noah LSM and has cires_ugwd. I know basically nothing about these schemes, (e.g., SSGWD/TOFD seems to refer to ugwpv1_gsldrag?)

I'm also not really clear what effect GFS_radiation_surface and mynnsfc_wrapper have vs. just sfc_diff. We can test whatever is recommended there.


```
diff suite_FV3_RRFS_v1nssl.xml suite_FV3_RRFS_v1nssl_lsmnoah.xml
3c3
< <suite name="FV3_RRFS_v1nssl"  version="1">
---
> <suite name="FV3_RRFS_v1nssl_lsmnoah" lib="ccppphys" ver="5">
18d17
<       <scheme>GFS_radiation_surface</scheme>
43c42
<       <scheme>mynnsfc_wrapper</scheme>
---
>       <scheme>sfc_diff</scheme>
48c47,48
<       <scheme>noahmpdrv</scheme>
---
>       <scheme>lsm_noah</scheme>
>       <!-- <scheme>noahmpdrv</scheme> -->
62a63
>       <scheme>rayleigh_damp</scheme>
73d73
<       <scheme>phys_tend</scheme>
```

2022-03-22 17:11 UTC, ligiabernardet commented
@MicroTed Can you please restate your questions? They were not clear to me. 

My understanding is that the suite with the NSSL mp will use cires_ugwp (same as RRFSv1_beta).  Do you have a concern about that?

Regarding the choice of surface layer scheme, are you saying that you have only tested the NSSL mp wit the GFS surface layer scheme, and you have little experience about its behavior when used with the MYNN surface layer scheme?

2022-03-22 18:00 UTC, MicroTed commented
@ligiabernardet Sorry -- I put a lot into one comment. The NSSL suite does include cires_ugwp, so that is fine. One question is, what is the difference between UGWv0 and SSGWD/TOFD? I guess these are namelist options, like do_ugwp and do_gsl_drag_tofd?
Thanks!

2022-03-29 17:46 UTC, gsketefian commented on tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0.sh
> +#
Edit the test description here to say WoFS_v0 instead of GFS_v16 (and add whatever else you see fit).

2022-03-29 17:46 UTC, gsketefian commented on tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_WoFS_v0.sh
> +#
Edit the test description here to say WoFS_v0 instead of RRFS_v1beta (and add whatever else you see fit).

2022-03-29 17:47 UTC, gsketefian commented on tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0.sh
> +#
RRFS_v1beta --> WoFS_v0

2022-03-29 17:58 UTC, gsketefian commented
@ywangwof For the 3 new WE2E tests that you're including, 

config.grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0.sh
config.grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_WoFS_v0.sh
config.grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0.sh

is there a reason to use different external models with the different resolutions (FV3GFS vs. NAM vs. HRRR/RAP)?

2022-03-29 18:03 UTC, ywangwof commented
No a specific reason. I just want to test the possible resolution 15 km/13 km/3 km and external models (FV3GFS/NAM/HRRR) combinations. Do you think I should add 9 test configurations, or just 3 tests with the same external model?

2022-03-29 19:13 UTC, ywangwof commented on tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0.sh
> +#
Modified in the newly added test configuration files.

2022-03-30 20:04 UTC, gsketefian commented
> No a specific reason. I just want to test the possible resolution 25 km/13 km/3 km and external models (FV3GFS/NAM/HRRR) combinations. Do you think I should add 9 test configurations, or just 3 tests with the same external model?
> 
> After today's discussion, I learned that the workflow E2E tests are not a set of comprehensive tests. Considering the main purpose of the Warn-on-Forecast project, I would like to add two test configurations only with this PR
> 
> _config.grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0.sh_ _config.grid_RRFS_SUBCONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0.sh_
> 
> Any further suggestion or comments? Thanks.

@ywangwof Sure.  Is it just to be able to test on a smaller domain?  FYI I'm going to add the 3km grid over Indianapolis probably tomorrow.

2022-03-31 23:36 UTC, gsketefian commented
> > No a specific reason. I just want to test the possible resolution 25 km/13 km/3 km and external models (FV3GFS/NAM/HRRR) combinations. Do you think I should add 9 test configurations, or just 3 tests with the same external model?
> > After today's discussion, I learned that the workflow E2E tests are not a set of comprehensive tests. Considering the main purpose of the Warn-on-Forecast project, I would like to add two test configurations only with this PR
> > _config.grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0.sh_ _config.grid_RRFS_SUBCONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0.sh_
> > Any further suggestion or comments? Thanks.
> 
> @ywangwof Sure. Is it just to be able to test on a smaller domain? FYI I'm going to add the 3km grid over Indianapolis probably tomorrow.

The 3km grid is in PR #725.

2022-04-01 20:36 UTC, gsketefian commented
@ywangwof I didn't mean to delay merging of this PR by my grid suggestion.  Let's get this in on whichever grids are currently available in the App.  We can then switch the tests to other grids if that makes more sense.  Do the tests

config.grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0.sh
config.grid_RRFS_SUBCONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0.sh

work right now?  If so, I can approve.

2022-04-01 20:48 UTC, ywangwof commented
config.grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0.sh works well.
config.grid_RRFS_SUBCONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0.sh still has a problem with the **ufs_weather_model**. I know it is an issue out-of our control. I am not sure whether we should push the PR or wait for a final fix or just drop the support of FV3GFS data? Any suggestion?

2022-04-01 21:32 UTC, gsketefian commented
@ywangwof I am ok with having only HRRR/RAP support in the App for now since it's better than nothing.  I will approve based on that.

Could you put the changes that are needed to the namelist to get FV3GFS to ICs/LBCs to work (that you sent in an email) in this PR or in a new issue so we know what needs to be done?  Thanks.

2022-04-01 21:32 UTC, gsketefian approved these changes

2022-04-01 21:55 UTC, ywangwof commented
In order for FV3GFS ICs/LBCs to work with WoFs suite, we should set `nssl_ccn_on = .false.` in _input.nml_ and drop the entry for `ccn_nc` in _field_table_.

2022-04-02 17:30 UTC, MicroTed commented
> 



> In order for FV3GFS ICs/LBCs to work with WoFs suite, we should set `nssl_ccn_on = .false.` in _input.nml_ a

I think there is a simple fix for this by setting the surface_value to zero for water_nc in the field_table (it needs to be zero, anyway, for just this circumstance where water_nc is not in the IC)

2022-04-05 19:58 UTC, MicroTed commented
> which will require PRs to fv3atm and ufs-weather-model to either change or add a suite and associated regression test.

@ligiabernardet My thinking was that the RT for v1nssl already tests the microphysics, so it wasn't clear that we need an additional RT for the wofs_v0 suite. If needed, I have changes to retool the v1nssl reg. test for wofs_v0.

I'm in the field this week, so I'm behind on a few things.

2022-05-17 21:57 UTC, ywangwof commented
A new [PR #772](https://github.com/ufs-community/regional_workflow/pull/772) to branch **_release/public-v2_** was issued. So this PR is closed and waiting for a final solution for restart reproducibility when blending > 0 with the ufs-weather-model repository. Just note that the restart reproducibility issue is not unique to this CCPP suite (WoFS_v0), but is a common bug for all regional workflows.

2022-05-17 21:57 UTC, closed without merging