Feature/gaea
ufs-community/regional_workflow pull request #734
Opened 2022-04-07 22:10 UTC by mark-a-potts

## DESCRIPTION OF CHANGES: 
Add machine specific files to allow the SRW app E2E tests to run successfully on Gaea. These changes include adding a <native> section to the FV3LAM template that specifies a cluster for slurm. This addition is required on Gaea and is not currently supported out of the box by Rocoto. Other machine specific files have been added as well.

## TESTS CONDUCTED: 
E2E tests below have been run successfully with the intel (18)/intelmpi on Gaea
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha

## DEPENDENCIES:
Add any links to external PRs. For example:
- ufs-community/ufs-srweather-app/pull/<pr_number>

## DOCUMENTATION:
If this PR is contributing new capabilities that need to be documented, please also include updates to the RST files in the ufs-srweather-app repository (docs/UsersGuide/source) as supporting material.

## ISSUE (optional): 
If this PR is resolving or referencing one or more issues, in this repository or elewhere, list them here. For example, "Fixes issue mentioned in #123" or "Related to bug in https://github.com/ufs-community/other_repository/pull/63"

## CONTRIBUTORS (optional): 
If others have contributed to this work aside from the PR author, list them here

2022-04-20 21:26 UTC, JeffBeck-NOAA requested changes
Looks good.  @mark-a-potts, do you mind updating the title of the PR?  Thanks!

2022-04-21 17:23 UTC, JeffBeck-NOAA approved these changes

2022-04-21 17:45 UTC, gsketefian commented on ush/machine/gaea.sh
> +      ;;
Remove the case statement's default stanza (i.e. lines 19-24) since it will add all kinds of badness to the `EXTR_MDL_SYSBASEDIR_ICS|LBCS` variables below (it will set them to the message being printed out and cause other downstream problems).  I had to do that for all the other machines.

2022-04-21 17:47 UTC, gsketefian commented on ush/machine/gaea.sh
> +# MET Plus is not yet supported on noaacloud
MET/METplus is not yet supported on gaea?  Change "noaacloud" to "gaea" if it's not supported.  Thx.

2022-04-21 17:49 UTC, gsketefian commented on ush/machine/gaea.sh
> +set -x
Remove `set -x` since that is now controlled from the wrapper script (`source_machine_file.sh`) via the `DEBUG` flag.

2022-04-21 17:57 UTC, gsketefian commented on ush/config_defaults.sh
> +EXTRA_SLURM_CMD=""
Suggestions on this:
1) Rename it to `SLURM_NATIVE_CMD` (or something similar with "native" in the name) so it is clearer it is associated with the "native" tag in the xml.
2) Move its definition down to line ~1694 (after `MAXTRIES_...`) since that group of variables are all/mostly values that get passed to the job scheduler like slurm.
3) Define what this parameter right before its definition, e.g. extra commands to pass to slurm via the "native" tag in the xml.
Thanks!

2022-04-21 18:45 UTC, mark-a-potts commented on ush/machine/gaea.sh
> +# MET Plus is not yet supported on noaacloud
I found a MET installation, but not a METplus install.

2022-04-21 18:45 UTC, mark-a-potts commented on ush/machine/gaea.sh
> +      ;;
Done.

2022-04-21 18:46 UTC, mark-a-potts commented on ush/machine/gaea.sh
> +# MET Plus is not yet supported on noaacloud
Changed noaacloud to gaea.

2022-04-21 18:46 UTC, mark-a-potts commented on ush/machine/gaea.sh
> +set -x
Done.

2022-04-21 19:01 UTC, mark-a-potts commented on ush/config_defaults.sh
> +EXTRA_SLURM_CMD=""
Thanks. I made these changes as well. I'll test them on gaea to make sure I didn't break anything.

2022-04-21 19:16 UTC, gsketefian commented on ush/machine/gaea.sh
> +      ;;
Thanks.

2022-04-21 19:17 UTC, gsketefian approved these changes
Looks good!

2022-04-21 19:17 UTC, gsketefian commented on ush/machine/gaea.sh
> +set -x
Thanks!

2022-04-22 01:16 UTC, merged