Standardize static data across Tier-1 platforms; fix and improve IC and LBC data retrieval
ufs-community/regional_workflow pull request #744
Opened 2022-04-20 16:50 UTC by mkavulich

## DESCRIPTION OF CHANGES: 
This PR implements the new static input data directory structures as described in [UFS SRW App Issue 231](https://github.com/ufs-community/ufs-srweather-app/issues/231). 

In addition, it fixes some issues with retrieving staged model input data from disk, and gives a way to specify whether or not to check alternate sources of data if not found on disk (HPSS, AWS). These flags have different defaults for different platforms based on data availability (for example, Cheyenne does not have NOAA HPSS access, and has no internet access on compute nodes, so both alternate sources have been turned off by default), and for WE2E tests that expect data staged on disk, these flags have been turned off.

Finally, some quality-of-life changes have been implemented, such as typo fixes, and reducing the number of tries for retrieving data from NOMADS from 20 failures (!) to 2.

## TESTS CONDUCTED: 
All tests run to completion on Hera (aside from known failures as documented in #728, #729, and #731). 

Tests on Cheyenne, Orion, and Jet are pending.

## DEPENDENCIES:
There are no PR dependencies for this PR, but data will need to be staged on disk on each platform before tests will run successfully. So far, data has been staged on Hera and Cheyenne, and should be staged

I will need assistance in getting data to other platforms from others who have access to those platforms.

## DOCUMENTATION:
Documentation for these changes and the new directory structure can be found in the [ufs-srweather-app issue #231](https://github.com/ufs-community/ufs-srweather-app/issues/231)

I was not sure what the best place to include this for version control is, but I wrote up a README file for the new "input_model_data" directory, attached here: 
[README_input_model_data.txt](https://github.com/ufs-community/regional_workflow/files/8523247/README_input_model_data.txt)

## ISSUE (optional): 
When merged, this PR will solve
 - #741
 - #742
 - https://github.com/ufs-community/ufs-srweather-app/issues/231

## CONTRIBUTORS (optional): 
@christinaholtNOAA

2022-04-21 13:23 UTC, chan-hoo commented
@mkavulich, COMINgfs (renamed to COMIN on PR #743) should not be removed from the regional workflow. NCO uses "COMIN" for defining paths to the input data.

2022-04-21 13:23 UTC, chan-hoo commented
@mkavulich, COMINgfs (renamed to COMIN on PR #743) should not be removed from the regional workflow. NCO uses "COMIN" for defining paths to the input data.

2022-04-22 17:30 UTC, mkavulich commented
@chan-hoo Thank you for your comment, I guess I was confused about our previous conversations on  Is there a reason to have a separate path to input data for nco mode? Why can't we just use the same variable for input data regardless of run mode? Is this simply a "requirement" for NCO standards to have this variable named in this particular way?

2022-04-22 19:04 UTC, chan-hoo commented
@mkavulich, I agree with you, but NCO would not. @BenjaminBlake-NOAA has much experience in this. Ben, can you answer to this?

2022-04-25 11:24 UTC, BenjaminBlake-NOAA commented
@mkavulich  You are correct, it is a requirement set by the NCO standards to define the location of input data as COMIN.  I agree that EXTRN_MDL_SOURCE_BASEDIR makes more sense, but we should leave it as COMIN for the NCO mode.  Thanks!

2022-04-25 12:19 UTC, JacobCarley-NOAA commented
@chan-hoo and @BenjaminBlake-NOAA are correct. See Table 1 in Section III of the Implementation Standards: https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf

2022-04-25 19:05 UTC, mkavulich commented
Data has now been staged in the new, standardized directory structure on the following platforms:
 - Hera
 - Jet
 - Orion
 - Cheyenne
 - WCOSS (I am actually unsure whether this was WCOSS or WCOSS2, whichever one is being actively used by the app with the "wcoss_dell_p3" machine file)
 - Gaea
 - Odin
 - Stampede
 - NOAA Cloud

I am running a full suite of tests on Jet currently since I did not get to that next week, but barring any surprises there I believe this PR is ready for review and merge once approved.

@chan-hoo I believe I have restored all the "COMGFS" instances, let me know if anything looks amiss on that front.

2022-04-25 23:58 UTC, venitahagerty commented
Machine: jet
Compiler: intel
Job: WE
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/autoci/pr/914443482/20220425232013/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-jet-intel-WE

2022-04-26 11:32 UTC, chan-hoo requested changes

2022-04-26 11:32 UTC, chan-hoo commented on ush/machine/orion.sh
> +TEST_COMIN="${staged_data_dir}/COMGFS"
Currently, the "COMGFS" directory is not under "${staged_data_dir}" on Orion (Hera, and WCOSS_DELL_P3 as well). It is located in "/work/noaa/fv3-cam/UFS_SRW_App/COMGFS". If you want to put COMGFS in ${staged_data_dir}, you should change "TEST_COMIN" on Orion, Hera, and WCOSS_DELL_P3 and move the data into ${stage_data_dir}.

2022-04-26 11:48 UTC, chan-hoo commented on ush/machine/hera.sh
>  TEST_COMIN="/scratch2/NCEPDEV/fv3-cam/noscrub/UFS_SRW_App/COMGFS"
@mkavulich, you put 'COMGFS' under ${staged_data_dir} on other machines.

2022-04-26 11:59 UTC, chan-hoo commented on ush/machine/orion.sh
> +TEST_COMIN="${staged_data_dir}/COMGFS"
@mkavulich, I've moved "COMGFS" into "${staged_data_dir}" on Orion and WCOSS_DELL_P3. However, I don't have permission for this on Hera.

2022-04-27 16:52 UTC, mkavulich commented on ush/machine/hera.sh
>  TEST_COMIN="/scratch2/NCEPDEV/fv3-cam/noscrub/UFS_SRW_App/COMGFS"
@chan-hoo I have updated this location on Hera; can you confirm that "/gpfs/dell2/emc/modeling/noscrub/UFS_SRW_App/COMGFS" is the correct location on WCOSS_DELL_P3?

2022-04-27 17:16 UTC, chan-hoo commented on ush/machine/hera.sh
>  TEST_COMIN="/scratch2/NCEPDEV/fv3-cam/noscrub/UFS_SRW_App/COMGFS"
@mkavulich, I've moved all the data to "/gpfs/dell2/emc/modeling/noscrub/UFS_SRW_App/develop/". Can you add 'staged_data_dir' to wcoss_dell_p3.sh as others?  staged_data_dir="/gpfs/dell2/emc/modeling/noscrub/UFS_SRW_App/develop" , and corresponding paths of FIXgsm, FIXaer, FIXlut, TOPO_DIR, SFC_CLIMO_INPUT_DIR, DOMAIN_PREGEN_BASEDIR, CCPA_OBS_DIR, MRMS_OBS_DIR, NDAS_OBS_DIR, TEST_COMIN, TEST_PREGEN_BASEDIR, TEST_EXTRN_MDL_SOURCE_BASEDIR with ${staged_data_dir}.

2022-04-27 17:28 UTC, chan-hoo commented
Regarding the python argument 'capture_output' @christinaholtNOAA removed in the above commit, the latest version of python available on the wcoss dell is 3.6.3. In this version, 'capture_output' is not supported. Thank you @christinaholtNOAA for this quick fix!

2022-04-28 00:13 UTC, mkavulich commented on ush/machine/hera.sh
>  TEST_COMIN="/scratch2/NCEPDEV/fv3-cam/noscrub/UFS_SRW_App/COMGFS"
@chan-hoo Thanks, I have updated the wcoss_dell_p3 machine file again, let me know if that looks correct.

2022-04-28 11:42 UTC, chan-hoo requested changes

2022-04-28 11:42 UTC, chan-hoo commented on ush/machine/wcoss_dell_p3.sh
> +staged_data_dir="/gpfs/dell2/emc/modeling/noscrub/UFS_SRW_App/develop/"
@mkavulich, can you remove '/' at the end of the line? staged_data_dir="/gpfs/dell2/emc/modeling/noscrub/UFS_SRW_App/develop"

2022-04-28 11:42 UTC, chan-hoo commented on ush/machine/wcoss_dell_p3.sh
> +DOMAIN_PREGEN_BASEDIR=${DOMAIN_PREGEN_BASEDIR:-"${staged_data_dir}/FIXLAM_NCO_BASE"}
@mkavulich, can you change the default directory "FIXLAM_NCO_BASE" => "FV3LAM_pregen"?  "${staged_data_dir}/FV3LAM_pregen"}

2022-04-28 15:26 UTC, mkavulich commented on ush/machine/wcoss_dell_p3.sh
> +staged_data_dir="/gpfs/dell2/emc/modeling/noscrub/UFS_SRW_App/develop/"
Done

2022-04-28 15:26 UTC, mkavulich commented on ush/machine/wcoss_dell_p3.sh
> +DOMAIN_PREGEN_BASEDIR=${DOMAIN_PREGEN_BASEDIR:-"${staged_data_dir}/FIXLAM_NCO_BASE"}
Done

2022-04-28 15:32 UTC, chan-hoo approved these changes

2022-04-28 20:25 UTC, gsketefian commented on ush/machine/cheyenne.sh
> +staged_data_dir="/glade/p/ral/jntp/UFS_SRW_App/develop"
As a precaution, can you add `local` in front of `staged_data_dir`?  Same in the other machine files.  Thx.

2022-05-03 04:36 UTC, mkavulich commented on ush/machine/cheyenne.sh
> +staged_data_dir="/glade/p/ral/jntp/UFS_SRW_App/develop"
@gsketefian When I do that, I am met with errors:

`line 54: local: can only be used in a function`

2022-05-03 04:49 UTC, JeffBeck-NOAA commented on ush/machine/cheyenne.sh
> +staged_data_dir="/glade/p/ral/jntp/UFS_SRW_App/develop"
@gsketefian, did you mean `local_staged_data_dir`?

2022-05-03 14:51 UTC, gsketefian commented on ush/machine/cheyenne.sh
> +staged_data_dir="/glade/p/ral/jntp/UFS_SRW_App/develop"
Oh right, this is not a function, just a script.  Ok, no worries then.  (@JeffBeck-NOAA no underscore, just wanted to make the variable local, but can't do that here.)

2022-05-03 17:21 UTC, JeffBeck-NOAA approved these changes

2022-05-03 17:35 UTC, gsketefian commented on tests/WE2E/run_WE2E_tests.sh
> +      EXTRN_MDL_SOURCE_BASEDIR_ICS="${EXTRN_MDL_SOURCE_BASEDIR_ICS}/${FV3GFS_FILE_FMT_ICS}/\${yyyymmddhh}"
Seems like `EXTRN_MDL_SOURCE_BASEDIR_ICS` should not be reset to include the yyyymmddhh since then it would no longer be a "base" directory.  Maybe use a different variable on the left-hand side instead?

2022-05-03 17:38 UTC, gsketefian commented on tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR.sh
> +EXTRN_MDL_FILES_ICS=( '{yy}{jjj}{hh}00{fcst_hr:02d}00' )
Why do these file formats need to be set explicitly?  Don't they have a default according to the external model being used?  Seems like they don't need to be set for FV3GFS but do for RAP and HRRR (and I guess NAM, but didn't see that one).

2022-05-03 17:42 UTC, panll approved these changes

2022-05-03 17:48 UTC, gsketefian commented on ush/config_defaults.sh
> +# DOMAIN_PREGEN_BASEDIR:
It seems like `DOMAIN_PREGEN_BASEDIR` is no longer only for NCO mode.  If that's the case, can we move it out of this section since this is only for NCO-mode variables?

Also, why not call it something like `FIXpregen` to fit in with all the other `FIX...` variables?

2022-05-03 18:17 UTC, mkavulich commented on tests/WE2E/run_WE2E_tests.sh
> +      EXTRN_MDL_SOURCE_BASEDIR_ICS="${EXTRN_MDL_SOURCE_BASEDIR_ICS}/${FV3GFS_FILE_FMT_ICS}/\${yyyymmddhh}"
@gsketefian the current code already modifies the existing variable by appending "${FV3GFS_FILE_FMT_ICS}/\${DATE_FIRST_CYCL}\${CYCL_HRS[0]}". If you're arguing to change how that works I would argue it needs a separate PR and should not continue holding up this one.

2022-05-03 18:20 UTC, mkavulich commented on tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR.sh
> +EXTRN_MDL_FILES_ICS=( '{yy}{jjj}{hh}00{fcst_hr:02d}00' )
@gsketefian There is a default, but the default is according to how it appears on HPSS and other sources. However, our static data for RAP and HRRR was sourced from Jet, which uses a different naming convention. We thought about renaming the static data to be consistent, but decided to leave it as it was and use it as an opportunity to test this capability to set filename templates in the config.sh file

2022-05-03 18:34 UTC, mkavulich commented on ush/config_defaults.sh
> +# DOMAIN_PREGEN_BASEDIR:
@gsketefian I have moved the variable definition out of the NCO section to a more relevant place. However, I'd argue against giving this a "fix" name because it is not fixed files analogous to the others, it is pregenerated data specific to these experiments.

2022-05-03 18:48 UTC, gsketefian commented on tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR.sh
> +EXTRN_MDL_FILES_ICS=( '{yy}{jjj}{hh}00{fcst_hr:02d}00' )
Ok, I see.  Sounds good.

2022-05-03 18:52 UTC, gsketefian commented on tests/WE2E/run_WE2E_tests.sh
> +      EXTRN_MDL_SOURCE_BASEDIR_ICS="${EXTRN_MDL_SOURCE_BASEDIR_ICS}/${FV3GFS_FILE_FMT_ICS}/\${yyyymmddhh}"
Ok.  This stuff got hacked quite a bit and will likely need a cleanup PR.  I'll look into that.

2022-05-03 18:55 UTC, gsketefian commented on ush/config_defaults.sh
> +# DOMAIN_PREGEN_BASEDIR:
Ok, makes sense.  Thanks.

2022-05-03 19:53 UTC, merged

2022-05-03 20:20 UTC, mkavulich commented
Thanks everyone for the reviews. For the future record, on the final hash (b4a7a1), the following tests were run successfully:

## Orion
 - community_ensemble_008mems
 - community_ensemble_2mems
 - deactivate_tasks
 - grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp
 - grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_HRRR
 - grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta
 - grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
 - grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUScompact_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
 - grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR
 - grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta
 - grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
 - grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2
 - grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
 - grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - grid_RRFS_NA_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta
 - grid_RRFS_SUBCONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2
 - grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - inline_post
 - MET_ensemble_verification
 - MET_verification
 - nco_ensemble
 - nco_grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
 - new_ESGgrid
 - new_GFDLgrid
 - new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_FALSE
 - new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_TRUE
 - pregen_grid_orog_sfc_climo
 - specify_DOT_OR_USCORE
 - specify_DT_ATMOS_LAYOUT_XY_BLOCKSIZE
 - specify_RESTART_INTERVAL
 - specify_template_filenames

The following tests failed:
 - grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha, GST_release_public_v1 (wallclock time on run_fcst)
 - subhourly_post, subhourly_post_ensemble_2mems (see #729)
 - nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16, nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km (investigating)
 - All "get_from_HPSS" tasks (no HPSS access)
 - grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v16 (see #731)
 - get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio (see #728) 

Will add further information as more tests complete.