Add code owners from EPIC
ufs-community/regional_workflow pull request #757
Opened 2022-05-05 17:39 UTC by gsketefian

## DESCRIPTION OF CHANGES: 
Add @gspetro-NOAA, @natalie-perlin, and @EdwardSnyder-NOAA to the `CODEOWNERS` file so they are notified of all PRs and can review them.

## TESTS CONDUCTED: 
None.

2022-05-05 17:46 UTC, JeffBeck-NOAA requested changes

2022-05-05 17:46 UTC, JeffBeck-NOAA commented on .github/CODEOWNERS
@gsketefian, can you remove @jwolff-ncar, the duplicates for Ratko and Ben, and fix Natalie's name (it's in italics)  Thanks!

2022-05-05 18:15 UTC, gsketefian commented on .github/CODEOWNERS
Done.

2022-05-05 18:16 UTC, chan-hoo approved these changes

2022-05-05 18:20 UTC, BenjaminBlake-NOAA requested changes
It looks like Natalie's name is still in italics, otherwise it looks good!

2022-05-05 18:21 UTC, gsketefian commented
> It looks like Natalie's name is still in italics, otherwise it looks good!

Yes, we had to invite her as a collaborator, waiting for her to accept.

2022-05-05 18:22 UTC, BenjaminBlake-NOAA approved these changes

2022-05-05 18:45 UTC, JeffBeck-NOAA approved these changes

2022-05-12 21:41 UTC, natalie-perlin commented
Thanks, found and and responded to invitation, all's good!

2022-05-13 01:54 UTC, merged