Feature/hera fix
ufs-community/regional_workflow pull request #791
Opened 2022-06-08 19:56 UTC by mark-a-potts

This PR fixes a number of issues related to both ci/cd and updating the UFS weather model to include CCPP-v6. 

References to lndp_each_step are removed due to changes in the input.nml on the UFS-WM side.

The miniconda version is now explicitly set for jet, so that the correct conda module gets loaded.

The "location" variable in ush/machine/hera.sh has been changed so that it does not point to an rstprod directory. (Maybe there is a better solution to this?) The role account on hera does not have rstprod access, so all e2e tests there were failing to launch previously. 

These changes will work in concert with ufs-srweather-app PR 293. https://github.com/ufs-community/ufs-srweather-app/pull/293

2022-06-08 21:17 UTC, EdwardSnyder-NOAA approved these changes

2022-06-08 21:43 UTC, JeffBeck-NOAA requested changes

2022-06-08 21:43 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
>  #
The comments above related to LSM_SPP_EACH_STEP need to be removed:

`# The default perturbation frequency is determined by the fhcyc namelist entry. Since that parameter is set to # zero in the SRW App, use LSM_SPP_EACH_STEP to perturb every time step.`

2022-06-08 21:44 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
>  #
@mark-a-potts, any information related to this namelist entry needs to be removed from the release documentation as well.  Attn: @gspetro-NOAA.

2022-06-08 21:54 UTC, mark-a-potts commented on ush/config_defaults.sh
>  #
We probably need to get a bit more info from Clara Draper, who made the change in the ufs-wm. These current changes are all still for testing, but I think we are getting closer. I now have the changes to the weather model all rolled up and part of their own branch under ufs-community.

2022-06-08 22:04 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
>  #
@mark-a-potts, yep, I was going to pull up her PR to get some more info on how things are handled now that this namelist entry has been removed.  It would be good to at least remove the comment above this namelist entry in config_defaults.sh.  I'm glad to hear you're much closer to getting the ufs-weather-model release branch finalized!

2022-06-10 18:33 UTC, mark-a-potts commented on ush/config_defaults.sh
>  #
Done.

2022-06-10 20:06 UTC, JeffBeck-NOAA approved these changes

2022-06-10 20:09 UTC, merged