added 'fix_dir_input_grid' var
ufs-community/regional_workflow pull request #795
Opened 2022-06-14 22:34 UTC by EdwardSnyder-NOAA

## DESCRIPTION OF CHANGES: 
Added back the `fix_dir_input_grid` variable to the `exregional_make_ics.sh` and `exregional_make_lbcs.sh` scripts.

## TESTS CONDUCTED: 
Ran test on Hera and more tests will be conducted through the Jenkins pipeline.

## DEPENDENCIES:
None.

## DOCUMENTATION:
No documentation changes needed.

## ISSUE (optional): 

## CONTRIBUTORS (optional): 
@mark-a-potts

2022-06-14 23:40 UTC, mark-a-potts requested changes
This looks good. I am not sure we need the parameter in exregional_make_ics.sh, but we can test it to make sure it doesn't break anything. Can you also switch over all the "develop" paths in ush/machine/*.sh to "v2p0" and we can combine two fixes into one?

2022-06-15 00:31 UTC, EdwardSnyder-NOAA commented
> This looks good. I am not sure we need the parameter in exregional_make_ics.sh, but we can test it to make sure it doesn't break anything. Can you also switch over all the "develop" paths in ush/machine/*.sh to "v2p0" and we can combine two fixes into one?

Made the changes as requested.

2022-06-15 00:39 UTC, mark-a-potts approved these changes

2022-06-15 11:48 UTC, merged

2022-06-15 19:59 UTC, gsketefian commented on scripts/exregional_make_lbcs.sh
> + 'fix_dir_input_grid': ${FIXgsm},
@EdwardSnyder-NOAA @mark-a-potts Just curious if you know whether this line was necessary to fix the `make_lbcs` failures.  If it was, it means something must have changed either in `chgres_cube` or the fix files.  To keep the namelist as simple as possible, it would be good to remove it if it's not really needed.  Not necessarily for this PR; I'm thinking more about when we move these changes into `develop`.  Thanks.

2022-06-15 20:06 UTC, mark-a-potts commented on scripts/exregional_make_lbcs.sh
> + 'fix_dir_input_grid': ${FIXgsm},
From our testing, it was definitely needed. I am not sure that it is needed for the exregional_make_ics.sh script, though. Without that line in the namelist, chgres_cube was looking for NULL/latlon.grid3.nc (or something very similar) and segfaulting when it could not open the file.

2022-06-15 20:49 UTC, gsketefian commented on scripts/exregional_make_lbcs.sh
> + 'fix_dir_input_grid': ${FIXgsm},
After digging into this a bit more, looks like this line was removed very recently from both files in PR #775.  I guess that was needed due to a change in UFS_UTILS (not sure what), but the `release/public-v2` branch still needs the lines (although I haven't actually tested the `develop` branch with the two tests that were failing in the release branch to see if it works; maybe I'll give that a shot now).