remove wcoss_dell_p3 from workflow
ufs-community/regional_workflow pull request #810
Opened 2022-07-14 16:59 UTC by chan-hoo

## DESCRIPTION OF CHANGES: 
As WCOSS1 goes away on 7/15/22, `wcoss_dell_p3` is removed from the UFS SRW App.

## TESTS CONDUCTED: 
- WE2E tests on Hera:
MET_verification
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta

2022-07-14 19:28 UTC, BenjaminBlake-NOAA commented on modulefiles/module-setup.csh.inc
>  else if ( { test -d /dcom -a -d /hwrf } ) then
This block is from the version of WCOSS that is even older than Mars/Venus/Luna/Surge (Tide and Gyre), so I suggest removing it.

2022-07-14 19:29 UTC, BenjaminBlake-NOAA commented on modulefiles/module-setup.sh.inc
>  elif [[ -d /dcom && -d /hwrf ]] ; then
Recommend removing this section for Tide and Gyre.

2022-07-14 19:30 UTC, BenjaminBlake-NOAA requested changes
The changes look good, I'd just recommend removing the sections for Tide and Gyre which no longer exist.

2022-07-15 10:57 UTC, chan-hoo commented on modulefiles/module-setup.csh.inc
>  else if ( { test -d /dcom -a -d /hwrf } ) then
@BenjaminBlake-NOAA, Removed.

2022-07-15 10:58 UTC, chan-hoo commented on modulefiles/module-setup.sh.inc
>  elif [[ -d /dcom && -d /hwrf ]] ; then
Removed.

2022-07-15 11:00 UTC, chan-hoo commented
@BenjaminBlake-NOAA, thank you for the comment. I've removed the blocks for Tide and Gyre from the if-statement.

2022-07-15 11:42 UTC, BenjaminBlake-NOAA approved these changes
@chan-hoo  Thanks for making the changes!

2022-07-18 19:23 UTC, JeffBeck-NOAA approved these changes

2022-07-19 13:07 UTC, merged